// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// GetUrlStatuserMock is a mock implementation of check_client.GetUrlStatuser.
//
//	func TestSomethingThatUsesGetUrlStatuser(t *testing.T) {
//
//		// make and configure a mocked check_client.GetUrlStatuser
//		mockedGetUrlStatuser := &GetUrlStatuserMock{
//			GetUrlStatusFunc: func(ctx context.Context, url string) (int, error) {
//				panic("mock out the GetUrlStatus method")
//			},
//		}
//
//		// use mockedGetUrlStatuser in code that requires check_client.GetUrlStatuser
//		// and then make assertions.
//
//	}
type GetUrlStatuserMock struct {
	// GetUrlStatusFunc mocks the GetUrlStatus method.
	GetUrlStatusFunc func(ctx context.Context, url string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetUrlStatus holds details about calls to the GetUrlStatus method.
		GetUrlStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockGetUrlStatus sync.RWMutex
}

// GetUrlStatus calls GetUrlStatusFunc.
func (mock *GetUrlStatuserMock) GetUrlStatus(ctx context.Context, url string) (int, error) {
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockGetUrlStatus.Lock()
	mock.calls.GetUrlStatus = append(mock.calls.GetUrlStatus, callInfo)
	mock.lockGetUrlStatus.Unlock()
	if mock.GetUrlStatusFunc == nil {
		var (
			nOut   int
			errOut error
		)
		return nOut, errOut
	}
	return mock.GetUrlStatusFunc(ctx, url)
}

// GetUrlStatusCalls gets all the calls that were made to GetUrlStatus.
// Check the length with:
//
//	len(mockedGetUrlStatuser.GetUrlStatusCalls())
func (mock *GetUrlStatuserMock) GetUrlStatusCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockGetUrlStatus.RLock()
	calls = mock.calls.GetUrlStatus
	mock.lockGetUrlStatus.RUnlock()
	return calls
}
