// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"url-checker/internal/repository/entity"
)

// UrlRepositoryMock is a mock implementation of repository.UrlRepository.
//
//	func TestSomethingThatUsesUrlRepository(t *testing.T) {
//
//		// make and configure a mocked repository.UrlRepository
//		mockedUrlRepository := &UrlRepositoryMock{
//			GetFunc: func(ctx context.Context, url string) (*entity.UrlInfo, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedUrlRepository in code that requires repository.UrlRepository
//		// and then make assertions.
//
//	}
type UrlRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, url string) (*entity.UrlInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *UrlRepositoryMock) Get(ctx context.Context, url string) (*entity.UrlInfo, error) {
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			urlInfoOut *entity.UrlInfo
			errOut     error
		)
		return urlInfoOut, errOut
	}
	return mock.GetFunc(ctx, url)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUrlRepository.GetCalls())
func (mock *UrlRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
